### ISSUE TITLE
Slope, Integral, and Locality support (was Previous value support)

### ISSUE THREAD

**Issue by joaquincasares** [jshook/metagener#5]
Example CSV scenario: stock symbol, last trade

I'd want each generated trade to be closely tied to the last trade with some knowledge of velocity, direction, and last value.

If the initial trade of the day was 40, I wouldn't want the next trade to be 20.

If the initial trade was 40 and all past trades have been positive, I don't want the day to end with 100 due to a snowball effect. Instead, I'd want 40 to be the anchor point that pulls the generated values' velocity towards the initial trade.

**Comment by jshook** [comment]
Let's break this one down a bit. There are a couple ways to approach this. It does get to the heart of the functional approach.

In order to represent a continuously connected stream of values, we simply have to support the right type of function. This is essentially a calculus problem, once we find a decent approximating function, we can deal with the integral and the derivative separately or together as we like. 

As well, you indicate that you want the trade values to hover near some specific value. In this case, it looks like it would be the initial value. I'd like to frame this as a combination of two functions. One being the initial value selector, and another being a variation away from it.

For this request, if we can come up with a slope & integral function pair which is reasonable for the task, I'll implement them directly as named and callable metagener functions. We can always add in the random starting point as a constant. We can also apply a logarithmic bias to the value to provide for some pressure to the original value. These are just functions, easy to implement, once we agree on one that is suitable.

I have some ideas on how to support interesting and difficult-to-predict slopes that are O(1) calculable,  obviously not periodic, but are static. The ability to pair them with a matching integral or derivative might be limited. For now, I'm considering using some reference points and smoothing functions to provide the appearance of the same.

If anybody has ideas on how to approach this from a more number theoretic perspective, please contact me and let's talk!

**Comment by jshook** [comment]
A function named fftsim has been implemented, which can add sin() components. For example, use fftsim(0.02,0.5,0.3,0.1) in order to create a two-component waveform with (xfreq,ymagnitude) tuples of (0.02,0.5) and (0.3,0.1). You can use as many of these value pairs as needed to create the desired level of variation. This is simply to support varying values for current needs. A more fully-featured form of this type of function will follow later.
